import { StyleSheet } from 'react-native';

const sharedShadow = {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
    boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.08)',
};

export const styles = StyleSheet.create({
    topText:{
        fontSize: 24,
        fontWeight: 'bold',
        fontStyle: 'normal',
        marginBottom: 10,
        textAlign: 'center',
        fontFamily: 'Segoe UI',
        color: '#333',
        lineHeight: 32,

    },
    stepBox:{
        position: 'relative',
        borderRadius: 20,
        backgroundColor: '#FFF',
        margin: 24,
        padding: 20,
        ...sharedShadow,
    },
    stepsText: {
        color: '#999',
        textAlign: 'center',
        fontFamily: 'Segoe UI',
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 20, 
    },
    helpIconButton: {
        position: 'absolute',
        top: 16,
        right: 16,
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: '#FFC4E1',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
        elevation: 3,
    },
    helpIconText: {
        color: '#FFF',
        fontWeight: 'bold',
        fontSize: 16,
        lineHeight: 18,
    },
    helpTooltipContainer: {
        backgroundColor: '#fff',
        borderRadius: 14,
        padding: 14,
        marginTop: 16,
        width: '100%',
    },
    helpTooltipHeader: {
        color: '#fff',
        fontFamily: 'Segoe UI',
        fontSize: 14,
        fontWeight: '700',
        backgroundColor: '#FF9ECD',
        padding: 8,
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
    },
    helpTooltipText: {
        color: '#000',
        fontFamily: 'Segoe UI',
        fontSize: 13,
        lineHeight: 20,
        borderColor: '#FF9ECD',
        borderWidth: 2,
        borderStyle: 'solid',
        ...sharedShadow,
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        borderBottomLeftRadius: 15,
        borderBottomRightRadius: 15,
        padding: 12,   
    },

    buttonsContainer:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 20,
        alignItems: 'flex-start',
        gap: 10,
    },

    optionsButtons:{
    backgroundColor: '#FFC4E1',
    padding: 10,
    borderRadius: 15,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    width: '48%',
    ...sharedShadow,
    },

    optionsButtonsHover: {
    backgroundColor: '#FF9ECD',
    //backgroundColor: '#E27D97',
    },

    optionsButtonsText:{
    color: '#FFF',
    textAlign: 'center',
    fontFamily: "Segoe UI",
    fontSize: 16,
    fontWeight: 'bold',
    lineHeight: 24, 
    },

    secondCakeButton:{
        backgroundColor: '#FFC4E1',
        padding: 10,
        borderRadius: 15,
        alignItems: 'center',
        display: 'flex',
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 12,
        width: '100%',
        ...sharedShadow,
    },

    filedBox: {
        marginTop: 20,
        width: '100%',
        alignSelf: 'center',
        borderWidth: 1,
        borderColor: '#FF9ECD',
        borderRadius: 15,
        padding: 10,
        display: 'flex',
        justifyContent: 'center',
        ...sharedShadow,
    },
    fildText: {
        fontSize: 18,
        color: '#717182',
        fontFamily: 'Segoe UI',
        fontStyle: 'normal',
        fontWeight: 400,
    },

    allergenRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },

    allergenOption: {
        backgroundColor: '#FFF',
        borderColor: '#FF9ECD',
        borderWidth: 1,
        borderRadius: 15,
        padding: 10,
        alignSelf: 'center',
        marginTop: 10, 
        display: 'flex',
        width: '48%',
        gap: 10,
        ...sharedShadow,
    },

    allergenContent: {
        flexDirection: 'row',
        alignItems: 'center',
        display: 'flex',
        gap: 10,
    },
    allergenOptionText: {
        color: '#333',
        fontSize: 14,
        fontFamily: 'Segoe UI',
        textAlign: 'left',
        fontWeight: '500',
        flexShrink: 1,
    },
    tickBox: {
        width: 20,
        height: 20,
        borderColor: '#FF9ECD',
        borderWidth: 1,
        borderRadius: 4,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFF',
    },
    tickMark: {
        fontSize: 14,
        color: '#FF9ECD',
        lineHeight: 16,
        fontWeight: 'bold',
    },

    getRecipeButton: {
        backgroundColor: '#FF9ECD',
        padding: 15,
        borderRadius: 25,
        alignItems: 'center',
        width: '60%',
        alignSelf: 'center',
        marginBottom: 20,
        ...sharedShadow,
    },
    getRecipeButtonText: {
        color: '#FFF',
        fontSize: 15,
        fontWeight: 'bold',
        alignContent: 'center',
        fontFamily: 'Segoe UI',
        textAlign: 'center',
        fontStyle: 'normal',
        lineHeight: 24,
    },
});
