import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({

    title: {
        color: '#FF9ECD',
        textAlign: 'center',
        fontFamily: "Segoe UI",
        fontSize: 24,
        fontStyle: 'normal',
        fontWeight: 700,
        lineHeight: 33.6,
    },
    title2:{
        color: '#999',
        textAlign: 'center',
        fontFamily: "Segoe UI",
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 20,
    },
    shoppingListContainer: {
        display: 'flex',
        alignSelf: 'center',
        marginTop: 20, 
        width: '80%',
        padding: 25.5,
        flexDirection: 'column',
        alignItems: 'flex-start',
        borderRadius: 20,
        borderWidth: 1.5,
        borderColor: '#FF9ECD',
        backgroundColor: '#FFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 15,
        elevation: 5,
    },
    shoppingListHeader: {
        display: 'flex',
        width: '100%',
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    shoppingListTitle: {
        color: '#FF9ECD',
        fontFamily: "Segoe UI",
        fontSize: 18,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 20,
        marginLeft: 10,
        
    },
    ingredientsList:{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        flexShrink: 0,
        alignSelf: 'stretch',
    },
    ingredients: {
        display: 'flex',
        padding: 8,
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'stretch',
        borderBottomColor: '#E5E5E5',
        borderBottomWidth: 1,
    },
    ingredientName: {
        display: 'flex',
        alignItems: 'center',
        color: '#333',
        fontFamily: "Segoe UI",
        fontSize: 16,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 24,
        textTransform: 'capitalize',
    },
    ingredientAmount: {
        display: 'flex',
        color: '#666',
        fontFamily: "Segoe UI",
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 20,
        marginLeft: 'auto',
    },
    recipeContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
    },
    recepieNameContainer: {
        display: 'flex',
        padding: 20,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'flex-start',
        gap: 9.268,
        backgroundColor: '#FF9ECD',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
        width: '80%',
        alignSelf: 'center',
        marginTop: 40,
    },
    recepieNameText: {
        display: 'flex',
        alignItems: 'center',
        color: '#FFF',
        fontFamily: "Segoe UI",
        fontSize: 18,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 20,
    },
    instructionsContainerRecipe: {
        display: 'flex',
        padding: 20,
        width: '80%',
        alignSelf: 'center',
        flexDirection: 'column',
        alignItems: 'flex-start',
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        backgroundColor: '#FFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 15,
        elevation: 5,
    },
    ingredientContainerRecipe: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        alignSelf: 'stretch',
        marginBottom: 10,
        borderBottomColor: '#E5E5E5',
        borderBottomWidth: 1,
    },
    ingredientHeader: {
        display: 'flex',
        color: '#FF9ECD',
        fontFamily: "Segoe UI",
        fontSize: 18,   
        fontStyle: 'normal',
        fontWeight: 500,
        lineHeight: 20,
        marginTop: 10,
        marginBottom: 10,
    },
    ingredientsRecipe: {
         display: 'flex',
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'stretch',
        marginBottom: 5,
    },
    instructionText: {
        display: 'flex',
        color: '#333',
        fontFamily: "Segoe UI",
        fontSize: 16,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 24,
    },
    noRecepieFoundText: {
        display: 'flex',
        color: '#999',
        fontFamily: "Segoe UI",
        fontSize: 16,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 24,
        textAlign: 'center',
        marginTop: 20,
    },
    tipsHeader: {
        display: 'flex',
        padding: 15,
        marginTop: 20,
        marginHorizontal: '10%',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FF9ECD',
        borderRadius: 15,
    },
    tipsHeaderText: {
        color: '#FFF',
        fontFamily: "Segoe UI",
        fontSize: 16,
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: 24,
    },
    tipsContainer: {
        display: 'flex',
        padding: 20,
        marginTop: 0,
        marginHorizontal: '10%',
        marginBottom: 20,
        flexDirection: 'column',
        alignItems: 'flex-start',
        backgroundColor: '#FFF',
        borderBottomLeftRadius: 15,
        borderBottomRightRadius: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 3,
    },
    tipTitle: {
        color: '#FF9ECD',
        fontFamily: "Segoe UI",
        fontSize: 16,
        fontStyle: 'normal',
        fontWeight: 600,
        lineHeight: 24,
        marginBottom: 12,
    },
    tipText: {
        color: '#333',
        fontFamily: "Segoe UI",
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: 400,
        lineHeight: 22,
        marginBottom: 10,
    },
    tipBold: {
        fontWeight: 600,
        color: '#FF9ECD',
    },
    
});

