import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
    welcomeSign: {
        textAlign: 'center',
        fontSize: 40,
        fontWeight: '700',
        fontStyle: 'normal',
        marginTop: 50,
        fontFamily: 'Segoe UI',
        color:'#333',
    },
    welcomeSign2: {
        fontSize: 40,
        fontWeight: '700',
        color: '#FF9ECD',
        textAlign: 'center',
        fontFamily: 'Segoe UI',
        marginBottom: 30,
    },
    createbutton: {
        marginTop: 30,
        backgroundColor: '#FF9ECD',
        borderRadius: 20,
        alignItems: 'center',
        width: '80%',
        alignSelf: 'center',
        padding: 10,
    },
    createbuttonText: {
        color: 'white',
        fontSize: 20,
        fontWeight: '400',
        paddingVertical: 10,
        paddingHorizontal: 20,
        textAlign: 'center',
        lineHeight: 28,
        fontFamily: 'Segoe UI',
    },
    addbutton: {
        marginTop: 20,
        backgroundColor: 'white',
        borderColor: '#FF9ECD',
        borderWidth: 2,
        borderRadius: 20,
        alignItems: 'center',
        width: '80%',
        alignSelf: 'center',
        padding: 10,
    },
    addbuttonText: {
        color: '#FF9ECD',
        fontSize: 20,
        fontWeight: '400',
        paddingVertical: 10,
        paddingHorizontal: 20,
        textAlign: 'center',
        lineHeight: 28,
        fontFamily: 'Segoe UI',
    },
});
